version: '3.3'

services:
  nfc_reader:
    build:
      context: "."
      dockerfile: ./env/Dockerfile
    container_name: nfc_reader
    command: "bash start.sh"
    # command: "sleep infinity"
    privileged: true
    volumes:
      - $PWD:/code